spec:
  functions:
  - url: functions/my_job.py
    name: func-a
    kind: job
    image: mlrun/mlrun
    handler: func_A
    with_repo: true
  - name: my-nuc-func
    kind: nuclio
    image: mlrun/mlrun
    handler: functions.my_nuclio:handler
    with_repo: true
  desired_state: online
  load_source_on_run: true
  source: git://github.com/amit-elbaz/nuclio-trigger-workflow.git#master
  workflows:
  - name: my-workflow
    path: workflows/workflow.py
  conda: ''
  origin_url: git@github.com:amit-elbaz/nuclio-trigger-workflow.git#refs/heads/master
metadata:
  name: nuclio-trigger-workflow-amite
kind: project
